name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: alpinelinux/build-base:latest
    steps:
      - run: df -h
      - uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false
      - run: df -h
      - uses: insightsengineering/disk-space-reclaimer@main
        with:
          docker-images: false
      - run: df -h
      - uses: actions/checkout@latest
        with:
          path: apkbuilds
      - env:
          RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
          RSA_PUBLIC_KEY: ${{ secrets.RSA_PUBLIC_KEY }}
        run: |
          set -ex

          sed -i 's/edge/v3.21/g' /etc/apk/repositories
          apk upgrade -U --available

          WORKSPACE="${GITHUB_WORKSPACE:-/github/workspace}"
          echo "Using workspace: $WORKSPACE"

          [ -n "$RSA_PRIVATE_KEY" ] || {
            echo "RSA_PRIVATE_KEY is empty"
            exit 1
          }
          [ -n "$RSA_PUBLIC_KEY" ] || {
            echo "RSA_PUBLIC_KEY is empty"
            exit 1
          }

          echo "$RSA_PRIVATE_KEY" >"$WORKSPACE/$GITHUB_REPOSITORY_OWNER.rsa"
          echo "$RSA_PUBLIC_KEY" >"$WORKSPACE/$GITHUB_REPOSITORY_OWNER.rsa.pub"
          chmod 600 "$WORKSPACE/$GITHUB_REPOSITORY_OWNER.rsa"

          export REPODEST="$WORKSPACE"
          export PACKAGER="eNV25 <env252525@gmail.com>"
          export PACKAGER_PRIVKEY="$WORKSPACE/$GITHUB_REPOSITORY_OWNER.rsa"

          for pkgdir in "$WORKSPACE"/apkbuilds/repo/*; do
            if [ -f "$pkgdir"/APKBUILD ]; then
              echo "=== Building package in $pkgdir ==="
              cd "$pkgdir"
              abuild checksum
              abuild -r
              abuild clean
            fi
          done

          ls -la "$WORKSPACE/repo/x86_64/"

      - uses: ncipollo/release-action@latest
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: repo/x86_64/*
          commit: f49fd0f5d8e228e300eda27f4aff45a0b1f9b861
          makeLatest: true
          removeArtifacts: true
          replacesArtifacts: true
          tag: x86_64
