name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@main
      - uses: insightsengineering/disk-space-reclaimer@main
      - uses: actions/checkout@v4
      - uses: ivanvc/abuild-releaser-action@v1.1.0
        with:
          author: eNV25 <env252525@gmail.com>
          rsa_public_key: ${{ secrets.RSA_PUBLIC_KEY }}
          rsa_private_key: ${{ secrets.RSA_PRIVATE_KEY }}
          alpine_branch: v3.21
