name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: alpinelinux/build-base:latest
    steps:
      - run: df -h
      - uses: jlumbroso/free-disk-space@main
        with:
          docker-images: false
      - run: df -h
      - uses: insightsengineering/disk-space-reclaimer@main
        with:
          docker-images: false
      - run: df -h
      - uses: actions/checkout@4
        with:
          path: apkbuilds
      - env:
          RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
          RSA_PUBLIC_KEY: ${{ secrets.RSA_PUBLIC_KEY }}
        run: /github/workspace/apkbuilds/build.sh
      - uses: ncipollo/release-action
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: repo/x86_64/*
          commit: f49fd0f5d8e228e300eda27f4aff45a0b1f9b861
          makeLatest: true
          removeArtifacts: true
          replacesArtifacts: true
          tag: x86_64
